name: scraper-daily

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2,4,12,14,16,18,21,23 * * *' # runs at 2,4,12,14,16,18,21,23 UTC everyday

jobs:
  scraper:
    runs-on: ubuntu-20.04
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          token: ${{ secrets.SCRAPER_SUTRAN_PAT }}
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7' # install the python version needed

      - name: execute my python script
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python scraper.py
      - name: commit my files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resultados_flourish.csv
          git commit --allow-empty -m "update data daily sutran" -a
      - name: push my changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SCRAPER_SUTRAN_PAT }}
          branch: main
          repository: annaabsi/sutran-data
          force: true
          github_url: https://github.com/