name: push-file-another-repo

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron: '10 2,4,12,14,16,18,21,23 * * *' # runs at 2,4,12,14,16,18,21,23 UTC everyday

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.SCRAPER_SUTRAN_PAT }}
      with:
        source_file: 'resultados_humano_flourish.csv'
        destination_repo: 'annaabsi/sutran-data'
        user_email: 'anna.absi@gmail.com'
        user_name: 'annaabsi'
        commit_message: 'actualizando datos bloqueo humano'
  copy-file-2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.SCRAPER_SUTRAN_PAT }}
      with:
        source_file: 'resultados_climatologico_flourish.csv'
        destination_repo: 'annaabsi/sutran-data'
        user_email: 'anna.absi@gmail.com'
        user_name: 'annaabsi'
        commit_message: 'actualizando datos bloqueo climatologico'